### ISSUE TITLE
Unify indentation

### ISSUE THREAD

**Issue by damianb** [trevorsenior/snoocore#100]
As on tin. Makes code editors that try to guess indentation methods very, very confused. And sad.

**Comment by trevorsenior** [comment]
This isn't the first time this has been an issue. I think emacs is a bit too smart for it's own good / it handles all indentation for me regardless of tab / space. I'll check it out in whitespace mode & fix problem areas. Thanks.

**Comment by damianb** [comment]
Tbh, you might want to look into a git hook to make the whitespace control automatic.

**Comment by trevorsenior** [comment]
I just got a [new plugin (ethan-wspace)](https://github.com/trevorsenior/dotfiles/blob/master/emacs/dot-emacs.d/custom/package-list.el#L59) to manage it and am now always using whitespace mode with [sane defaults](https://github.com/trevorsenior/dotfiles/blob/master/emacs/dot-emacs.d/custom/pkgconf/whitespace-mode/index.el).

I'll look into git hooks for this sort of thing though.
