### ISSUE TITLE
X-Modhash required even with Oauth

### ISSUE THREAD

**Issue by a9io** [trevorsenior/snoocore#104]
` Potentially unhandled rejection [4] Error: value required in setHeader("X-Modhash", value).`
`    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:312:11)`
`    at new ClientRequest (_http_client.js:77:14)`
`    at Object.exports.request (http.js:30:10)`
`    at Object.exports.request (https.js:117:15)`

**Comment by trevorsenior** [comment]
I can probably help you out better here than on IRC - thanks :wink: 

It looks like you're using an older version of the library that relies on superagent still. 

Can you confirm the version of Snoocore that you are using? The current version is `2.7.1`

**Comment by a9io** [comment]
Roger that, 2.7.1

**Comment by a9io** [comment]
I am using an older example for auth though.

    var reddit = new Snoocore({
      userAgent: "bot",
      login: {
        username: "**",
        password: "**"
      },
      oauth: {
        type: 'script',
        consumerKey: '**',
        consumerSecret: **',
        scope: ['flair', 'identity', "read", "submit"]
      }
    });

**Comment by trevorsenior** [comment]
Hrm, that example should still work fine.

When specifically do you get the error? When you initialize the library, when you're authenticating, or when you make a call to an endpoint?

If it happens when you're making a call to an endpoint which endpoint are you trying to use? (I think it's https://www.reddit.com/dev/api#POST_api_submit , but just making sure).

Just narrowing down the problem!

**Comment by a9io** [comment]
Endpoint is GETting from a sub's /comments/.

**Comment by trevorsenior** [comment]
I assume that you're trying to use `/r/all/comments.json`

Unfortunately you've hit an endpoint that is not supported by OAuth. I'll open a new thread on /r/redditdev about it. You can get around it for now (though it's quite nasty) by using `reddit.raw` and bypassing authentication.

http://tsenior.com/snoocore/undocumentedEndpoints.html <-- reddit.raw information
http://tsenior.com/snoocore/callContextOptions.html#bypassAuth <-- bypass authentication

Sample code that should work:

```javascript
var Snoocore = require('snoocore');

var reddit = new Snoocore({
  userAgent: 'foobar',
  login: {
    username: 'tsenior',
    password: 'sten3_INVALID_stese#e'
  },
  oauth: {
    type: 'script',
    consumerKey: 'pu_invalid_gwnLw',
    consumerSecret: '296mX_invalid_Hy8g2g',
    scope: [ 'identity', 'read' ]
  }
});

reddit.auth().then(function() {
  return reddit('/api/v1/me').get();
}).then(function(result) {
  console.log(result);

  var endpoint = 'https://www.reddit.com/r/all/comments.json';
  return reddit.raw(endpoint).get({}, { bypassAuth: true });

}).then(function(result) {
  // the comments from /r/all
  console.log(result);
}).catch(function(error) {
  // oh no!
  console.error('---- ERROR ----');
  console.error(error);
});
```

**Comment by a9io** [comment]
TY!

**Comment by a9io** [comment]
I seem to be getting the error for posting comments now too. Same deal?

**Comment by trevorsenior** [comment]
Yeah, it's not the best fix in the world. Once it's included in reddit's OAuth endpoints it'll behave better.

As for posting comments, that works fine as it's in the OAuth spec. Using the endpoint:

https://www.reddit.com/dev/api#POST_api_comment

say we want to add a comment to this comment:

https://www.reddit.com/r/snoocoreTest/comments/2jcv7x/nested_comments/cp2kyam

The "fullname" for this comment is "t1_cp2kyam" so we can use it like so:

```javascript
var Snoocore = require('snoocore');

var reddit = new Snoocore({
  userAgent: 'foobar',
  login: {
    username: 'tsenior',
    password: '...'
  },
  oauth: {
    type: 'script',
    consumerKey: '...',
    consumerSecret: '...',
    scope: [ 'identity', 'read', 'submit' ]
  }
});

reddit.auth().then(function() {
  return reddit('/api/v1/me').get();
}).then(function(result) {
  console.log(result);
  return reddit('/api/comment').post({
    text: 'test post @ ' + new Date(),
    thing_id: 't1_cp2kyam'
  });
}).then(function(result) {
  console.log(result);
});
```

**Comment by a9io** [comment]
Ok, thanks

**Comment by trevorsenior** [comment]
Did the `/api/comment` example work for you?

**Comment by a9io** [comment]
Yeah, I have already been using that so it usually works. I'm pretty sure at this point I'm more concerned about the get api

**Comment by a9io** [comment]
Hmm, It seems that if I attempt to comment more than once in a given moment, I'll get the X-Modhash error.

**Comment by a9io** [comment]
It will only comment once if the entire program is restarted. Methinks something liek the snoocore should be called again?

I tried doing .auth() every time I wanted to comment, to no sucess in fixing.

**Comment by trevorsenior** [comment]
Can you give a full example that reproduces this? I can't reproduce the error myself when testing various things.

You only need to auth once and then you're good to make as many comments as you'd like. Here is a modified version of the above that will comment 3 times in a row:

```javascript
var Snoocore = require('snoocore');
console.log(Snoocore.version); // 2.7.1
var when = require('when'); // promise library (https://github.com/cujojs/when)

var reddit = new Snoocore({
  userAgent: 'foobar',
  login: {
    username: 'tsenior',
    password: '***'
  },
  oauth: {
    type: 'script',
    consumerKey: '***',
    consumerSecret: '***',
    scope: [ 'identity', 'read', 'submit' ]
  }
});


function postComment() {
  return reddit('/api/comment').post({
    text: 'test post @ ' + new Date(),
    thing_id: 't1_cp2kyam'
  });
}

reddit.auth().then(function() {
  // post a comment 3 times
  return when.all([
    postComment(),
    postComment(),
    postComment()
  ]);
});
```

**Comment by a9io** [comment]
I'll do that in a bit. I didn't use the `return` keyword in my code, not sure if that matters

**Comment by a9io** [comment]
I tried to reproduce it too, to no avail :(

In the end, I just requested a modhash myself using this, and set line 420 of snoocore.js to the result. It works fine. Let me know if you have *any* theories on why this worked, otherwise thanks for the help!

    var request = require('request').defaults({jar: true});
    
    var login = function(fn) {
            request({
                uri: 'http://www.reddit.com/api/login',
                method: 'POST',
                headers: {
                    'User-Agent': ""
                },
                form: {
                    user: "",
                    passwd: "",
                    rem: 'False'
            }
        }, function (error, response) {
            if (!error && response.statusCode == 200) {
                getModhash(fn);
            } else {
                console.log("Could not log in");
            }
        });
    };

    var getModhash = function(fn){
      request({
          uri: 'http://www.reddit.com/api/me.json',
          method: 'GET',
          headers: {
              'User-Agent': ""
          }
      }, function (error, response) {
          if (!error && response.statusCode == 200) {
              fn(JSON.parse(response.body).data.modhash);
          } else {
              console.log("couldnt get modhash");
          }
      });
    };

    module.exports = exports = {
      grab: function(fn){
        login(function(hash){
          fn(hash);
        });
      }
    };

**Comment by trevorsenior** [comment]
Hey sorry about the late response. I'm out of my country / on vacation so my replies are slow. I'll take a look at this code when I return.

**Comment by a9io** [comment]
It's all good, everything's working fine so far :+1:
