### ISSUE TITLE
403 error when attempting to post comment

### ISSUE THREAD

**Issue by BalloonInd** [trevorsenior/snoocore#109]
I am trying to post a comment and I am getting a 403 error.

Here's my code:

            function postComment() {
                reddit.raw('http://www.reddit.com/api/me.json').get({
                }).then(function(data) {
                    var commentText = document.getElementById("response").value;
                    reddit('/api/comment').post({
                        api_type: 'json',
                        thing_id: getUrlVars()['link'],
                        text: commentText,
                        uh: data.data.modhash
                    });
                });
            }

I would think this would work, but it does not seem to.

**Comment by trevorsenior** [comment]
What are the values of `thing_id` and `text` in your code snippet above? Usually I forget to use a ["fullname"](https://www.reddit.com/dev/api#fullnames) when filling in the value of `thing_id`.

Here is an example of the comment api in use (a full contained example in node.js)
https://github.com/trevorsenior/snoocore/issues/104#issuecomment-76883529

**Comment by BalloonInd** [comment]
Yep, you're right. I forgot the t3_ portion of the fullname. Thanks! I hate to do this, but I'm about to have another question too! Almost done creating a Reddit browser based on this though, and possibly stock analysis software too!

**Comment by trevorsenior** [comment]
No problem. I don't mind helping out.
