### ISSUE TITLE
How do you get information on what posts you've liked

### ISSUE THREAD

**Issue by BalloonInd** [trevorsenior/snoocore#112]
I am trying to figure out how whether a particular user liked a post (in order to style buttons correctly, etc)

The only way I can figure out how to do it is to get a listing of all liked or disliked comments, and then iterating through them.

That's obviously very, very inefficient.

Is there a better way to do this?

**Comment by trevorsenior** [comment]
When you query for a listing of things. These can be posts as in `/hot` or comments as in `/r/aww/comments/$articleId`. Both have an several attributes in the listing:

- `saved` lets you know if the user has saved the comment/post.
- `likes` lets you know if the user has voted on a post (up or down)
  - `null` - user has not voted on the thing
  - `true` - upvote
  - `false` - downvote

As an example view this listing in your browser: 

https://www.reddit.com/r/aww.json

then upvote / downvote / save the top post in /r/aww to see the change.

**Comment by BalloonInd** [comment]
Beautiful, thanks again!

**Comment by trevorsenior** [comment]
No problem.
