### ISSUE TITLE
Is it possible to pull a comment and children?

### ISSUE THREAD

**Issue by BalloonInd** [trevorsenior/snoocore#113]
I want to pull a specific comment and its children, instead of the entire article (for speed and efficiency when updating).

Is there an endpoint that allows that?

Also, thanks once again for all your help.

**Comment by damianb** [comment]
[yes,](https://www.reddit.com/dev/api/#GET_api_info), I think. also [of note](https://www.reddit.com/dev/api/#GET_comments_{article}).

for future reference, i would suggest trying #reddit_dev (freenode irc) first, as it's the more appropriate avenue for reddit development & api questions.

**Comment by BalloonInd** [comment]
The first only pulls a specific comment. The second gives me what I want, but does not provide only the json.

And I'll double check reddit_dev, thank you.

**Comment by BalloonInd** [comment]
reddit.raw('/r/subreddit/comments/' + link + ".json?comment=" + id + "&context=0").get({
                    }).then(function(data) {
                    console.log(data);
                });

Works for me to get the JSON for a particular comment.

**Comment by trevorsenior** [comment]
Did you ever figure this out?

**Comment by BalloonInd** [comment]
Yes I did. I'm very busy right now, but I can make a comment later on about how I accomplished this if you want.

**Comment by trevorsenior** [comment]
Oh no that's fine. I was just curious / wanted to close the issue if it was resolved. Thanks!
