### ISSUE TITLE
/api/saved_categories should be get request

### ISSUE THREAD

**Issue by premii** [trevorsenior/snoocore#114]
reddit('/api/saved_categories') returns post object. It should be get

http://www.reddit.com/dev/api#GET_api_saved_categories

**Comment by trevorsenior** [comment]
You are right. It [should be working](https://github.com/trevorsenior/snoocore/blob/2.7.2/build/api.json#L795) but it isn't. I reproduced your issue with:

```javascript
var Snoocore = require('Snoocore');

var reddit = new Snoocore({
  userAgent: 'loginTest',
  login: {
    username: 'test1232eee',
    password: '11111111'
  }
});

reddit.login().then(function() {
  return reddit('/api/me.json').get();
}).then(function(result) {

  var call = reddit('/api/saved_categories');

  console.log(call);

  return reddit('/api/saved_categories').get();
}).then(function(result) {
  console.log(result);
});
```

```
{ post: [Function] }
Potentially unhandled rejection [1] TypeError: Object #<Object> has no method 'get'
    at /Users/trev/tmp/foo.js:19:42
    at tryCatchReject (/Users/trev/tmp/node_modules/Snoocore/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/trev/tmp/node_modules/Snoocore/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/trev/tmp/node_modules/Snoocore/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/trev/tmp/node_modules/Snoocore/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/trev/tmp/node_modules/Snoocore/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/trev/tmp/node_modules/Snoocore/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)
```

Thanks for the report.

**Comment by trevorsenior** [comment]
Figured it out.

Reddit [removed `.json` extensions](https://web.archive.org/web/20150108075820/http://www.reddit.com/dev/api#GET_api_saved_categories.json) from their endpoints sometime in the last few days. In version `3.0.0` Snoocore will not rely so heavily on the API documentation and instead be more lenient in what it allows. This will be patched in a minor version. I'll ping back here when it is working.

<sub>You may be able to use `reddit('/api/saved_categories.json')` in the meantime</sub>

**Comment by trevorsenior** [comment]
Seems like there *may* be an issue on reddit's end for this endpoint as well. I've opened a new thread over at /r/redditdev to see if anyone can help there.

https://www.reddit.com/r/redditdev/comments/2z58bd/apisaved_categories_throws_403/

**Comment by trevorsenior** [comment]
Let me know if it works for you in `2.7.3` - I may have to make a slight patch later in the day / week for a browser related fix.
