### ISSUE TITLE
Missing params in setHeader()

### ISSUE THREAD

**Issue by martellaj** [trevorsenior/snoocore#117]
*Disclaimer*: I'm new to JavaScript, Node.js, and your module.

I'm able to post in a thread using this code:

```javascript
reddit.auth()
.then(function() {
    reddit('/api/comment').post({
        api_type: 'json',
        text: requestArgs.text,
        thing_id: requestArgs.thing_id
    })
    .then(function(data) {
        console.log('Successfully posted in: ' + threadTitle); 
    }, function(error, threadTitle) {
        chillOut(error, threadTitle);
    })
    .done();
}, function(error) {
    console.log("Auth failed in chillOut."); 
})
```

The comment is posted, but the error callback is also execute because there's an error:

```
Successfully posted in: I don't have flair either.
[Error: "name" and "value" are required for setHeader().]
Entered chillOut for thread: undefined
/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at chillOut (/Users/martellaj/Repositories/link-flair-bot/reddit.js:77:29)
    at /Users/martellaj/Repositories/link-flair-bot/reddit.js:95:17
    at tryCatchReject (/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/martellaj/Repositories/link-flair-bot/node_modules/snoocore/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)
```

So am I supposed to define "name" and "value" somewhere? Or is that the module's responsibility?

**Comment by trevorsenior** [comment]
> I'm new to JavaScript, Node.js, and your module.

No problem!

I'll take a look at the code and see if I can reproduce it. Your use of promises may be causing some issues, but I'll report back after a little investigation.

**Comment by martellaj** [comment]
Awesome. I'm still a little unclear with the whole promise paradigm, but am using the second error function because I was getting errors without them about possible unhandled error or something.

**Comment by trevorsenior** [comment]
Can you provide a *contained* / *complete* code snippet that reproduces the problem? I wasn't able to reproduce the problem.

- - -

The following code works. It posts a comment without any errors popping up. The account details below should work (it's a throwaway account) so feel free to give it a go without replacing it with your account details.

```javascript
var Snoocore = require('snoocore');
console.log(Snoocore.version); // 2.7.3

var reddit = new Snoocore({
  userAgent: '/api/saved_categories test user agent',
  login: {
    username: 'test1232eee',
    password: '11111111'
  },
  oauth: {
    type: 'script',
    consumerKey: '5CpXdCBM51JxIg',
    consumerSecret: 'unYvgfSgyeV59eLWY9SzxOlmMuY',
    scope: [ 'identity', 'submit' ]
  }
});

reddit.auth().then(function() {
  return reddit('/api/v1/me').get();
}).then(function(result) {
  console.log(result);
  return reddit('/api/comment').post({
    text: 'test post @ ' + new Date(),
    thing_id: 't1_cp2kyam'
  });
}).then(function(result) {
  console.log(result);
});
```

- - - 

## Promises

As for promises once you fully understand them, they're great. I'd recommend finding a good article on them / some sample code that explains them well. I'll give a brief overview of what I noticed in your code.

### Chaining 

One thing I noticed was that you were not chaining promises.

Assume that `fnA`, `fnB`, and `fnC` all return promises.

```javascript
// Chaining. Useful to avoid code that goes out forever ----->
// Will print the result of A, B, and C as they execute
return fnA().then(function(resultA) {
  console.log(resultA);
  return fnB();
}).then(function(resultB) {
  console.log(resultB);
  return fnC();
}).then(function(resultC) {
  // we can only print the result of C
  console.log(resultC);
});

// Nested promises are fine as well. This is what you were doing.
// Only do this if you need to use multiple values for a single
// call. Below I'm printing resultA, B, and C in a single console.log
// This is fine!
return fnA().then(function(resultA) {
  return fnB().then(function(resultB) {
    return fnC().then(function(resultC) {
      // now we can print all 3!
      console.log(resultA, resultB, resultC);
    });
  });
});

// A mix of chaining / nesting.
return fnA().then(function(resultA) {
  return fnB().then(function(resultB) {
    console.log(resultA, resultB);
    return fnC();
  }).then(function(resultC) {
    console.log(resultA, resultC);
  });
});
```

## Return promises in `.then`

If you intend to keep a promise chain going, you'll need to return promises and not just call them

```javascrpit
// WRONG!
return fnA().then(function() {
  fnB(); // missing return
}).then(function(resultB) {
  console.log(resultB); // undefined!
});

// correct!
return fnA().then(function() {
  return fnB();
}).then(function(resultB) {
  console.log(resultB); // some value
});
```

## Use of `.done`

The use of `.done` should really be used at the end of a promise chain unless you know what you're getting into. There is some debate if you should even use it at all but that's another discussion.

```javascript
// WRONG!
return fnA().then(function() {
  return fnB().done(); // does not return a promise!
}).then(function(resultB) {
  console.log(resultB); // undefined!
});

// correct!
return fnA().then(function() {
  return fnB();
}).then(function(resultB) {
  console.log(resultB); // some value
}).done(); // throws any remaining errors
```

**Comment by martellaj** [comment]
You can find the code here: https://github.com/martellaj/link-flair-bot. Specifically in the reddit.js file. I'm thinking the problem lies in multiple calls at the same time? See the processPosts function. I'm working with a test sub (/r/martellaj) where I have 2 threads I want to post in. Consistently, my app posts in one and fails in one.

**Comment by martellaj** [comment]
I've done some digging. This is the output of a run:

```
>>> headers
 { 'User-Agent': 'Link-Flair-Bot by martellaj',
  'X-Modhash': '',
  Authorization: 'bearer 37702741--R2YGA_QWfS6zS5jedESob6kFx8',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Content-Length': 57 }
Successfully posted in: Text post with no flair.

>>> headers
 { 'User-Agent': 'Link-Flair-Bot by martellaj',
  'X-Modhash': undefined,
  Authorization: 'bearer 37702741--R2YGA_QWfS6zS5jedESob6kFx8',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Content-Length': 57 }
Failed to post in: I don't have flair either.
[Error: "name" and "value" are required for setHeader().]

>>> headers
 { 'User-Agent': 'Link-Flair-Bot by martellaj',
  'X-Modhash': undefined,
  Authorization: 'bearer 37702741--R2YGA_QWfS6zS5jedESob6kFx8',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Content-Length': 57 }
Failed to post in: I don't have flair.
[Error: "name" and "value" are required for setHeader().]
```

Looks like 'X-Modhash' is not being defined before some of the requests and that is causing the error.

**Comment by martellaj** [comment]
I have a super hacky fix for this. I'm not sure WHY the X-Modhash header becomes undefined after the first call, but I did add code to work around it. I added the following snippet in **requestNode.js** in the *https* function.

```
if (options.headers.hasOwnProperty('X-Modhash') && 
      typeof options.headers['X-Modhash'] === 'undefined') {
    // console.log('Adjusted \'X-Modhash\' header.');
    options.headers['X-Modhash'] = ''; 
  }
```

Please let me know if you find the source of the error. I wasn't able to figure it out.

**Comment by trevorsenior** [comment]
Hey there, sorry for not posting back sooner. I've been really busy with courses here and won't be really free till next week.

However, I'll take a quick look at your source and see what I find. You really shouldn't need a modhash  when using OAuth so I'm a bit confused why an empty string for it would fix your issue.

**Comment by martellaj** [comment]
No worries! I don't think the problem is with the HTTP request, but just the setHeader function that's used to set the request's headers. The function requires the name and value of the header, which apparently cannot be "undefined", as far as I can tell.

But yeah, the fix you described is what that snippet does. I just couldn't find out why the value is undefined AFTER the first request. The first request always works and the value is always an empty string.

**Comment by trevorsenior** [comment]
I'm fine with a patch to `requestNode.js` with your provided code. Go ahead and make a pull request and I'll merge it in.
