### ISSUE TITLE
when refereshing access token. How can you get the new access token

### ISSUE THREAD

**Issue by techsin** [trevorsenior/snoocore#120]
http://tsenior.com/snoocore/oauth-explicit.html

at here it says that refresh you provide the refresh token and it automatically refreshes which is fine but how do you get the new refresh token. if you plan to make calls later on but not later enough (<1 hour)...

**Comment by trevorsenior** [comment]
Are you referring to:

> This will allow Snoocore to automatically refresh the access_token when it expires after an hour of continuous use.

?

The refresh token never changes. It's strictly used to get new access tokens. Are you looking for a way to get the new access tokens?

You should be able to use the same refresh token over and over to re-authenticate with `reddit.refresh` regardless of when you call `reddit.refresh`. If you call `reddit.refresh` using the same refresh token within an hour that is fine -- Snoocore will be authenticated with different access tokens, but it should still work.

Does that help out any? Let me know if you ran into any issues in particular.

**Comment by trevorsenior** [comment]
Oh I read you post and not the post's title. I think you're looking for a way to get the access token after Snoocore refreshes it?

There isn't a current elegant way to do this. Would a new event solve the issue? e.g.

```javascript
reddit.on('access_token_refreshed', function(newAccessToken) {
   // do something with the new access token
});
```

**Comment by trevorsenior** [comment]
I haven't heard back, so I'll probably get to this this weekend. I'm also curious about your use case for this.

**Comment by techsin** [comment]
so i making my client do the grunt work while my server app just refresh
and send the new access token to it over ssl.
This way my app can be client sided and still have longer than 1 hour
access.

I don't want my user to relogin and after every 1 hour. So each time
someone wants to use my site they gotta login. Even in same day. Which is
annoying originally when i envisioned it, when i didn't know anything about
reddit api and its limits, i thought of like this.. user logs in, my app in
browser does its stuff thats it. But no process starts all over every time.

**Comment by trevorsenior** [comment]
Ah thanks, I'll keep that in mind when working on this.

**Comment by techsin** [comment]
Really Appreciate...going over your source code has helped me understand
reddit api a lot.

**Comment by trevorsenior** [comment]
Another question. What does your initial config look like on the clients? 
How are you setting the access token on the clients? I want to provide 
a clean interface for this (instead of setting internal variables).

Glad the source has helped! It grew into a mess of code over time as new
features were added. The 3.0.0 branch addresses this for the most part
breaking the code into proper modules.

**Comment by techsin** [comment]
on client i just use access token as long as possible and if error occurs
then new access token is requested from my server.
At start client send unique id to server via cookie.
If server finds access token for that id then it sends the access token,
also refresh it if it's been more than 1 hour.
If id is not present or can't be found then new session is created.

**Comment by trevorsenior** [comment]
Okay. This should be finished tomorrow. I'm working out some
test cases at the moment. I've updated the documentation
with the new functions that will be exposed in version `2.8.0`.

**Comment by trevorsenior** [comment]
@techsin pushed some new functions in `2.8.0` to npm.

Let me know if these solve your issue. Documentation: 

http://tsenior.com/snoocore/miscellaneous-oauth-fns.html

- - -

Keeping this issue open till these new functions / events are 
made in the 3.0.0 branch.

**Comment by trevorsenior** [comment]
@techsin Also the new event `access_token_refreshed`

http://tsenior.com/snoocore/events.html

**Comment by techsin** [comment]
this is great yesterday i spent 5 hours writing my own module from start to
finish to get code lol
