### ISSUE TITLE
Initial calls shouldn't need to fail. Check if the access token is set to invalid first.

### ISSUE THREAD

**Issue by trevorsenior** [trevorsenior/snoocore#123]
The issue:

![Issue](http://i.imgur.com/4kn5yWY.jpg)

We can improve this by checking if the access token is invalid ([#L22](https://github.com/trevorsenior/snoocore/blob/3.0.0/src/OAuth.js#L22)) and avoid this slowdown.

**Comment by saiichihashimoto** [comment]
https://gitter.im/trevorsenior/snoocore?at=5547e0dd26b588274527abd3

It looks like the gap between the access_token and retrying the intial call is always ~5s

**Comment by trevorsenior** [comment]
#124 addresses the "bug" label that was added / removed for this issue.
