### ISSUE TITLE
When authenticating, if reddit's servers are down, the script will crash

### ISSUE THREAD

**Issue by a9io** [trevorsenior/snoocore#127]
Snoocore seems to have a hard time sometimes when looking for a proper response from reddit:

    > [Error: Failed to get Auth Data:
    - <!doctype html><html><title>Ow! -- reddit.com</title><style>body{text-align:center;position:absolute;top:50%;margin:0;margin-top:-275px;width:100%}h2,h3{color:#555;font:bold 200%/100px sans-serif;margin:0}h3,p{color:#777;font:normal 150% sans-serif}p{font-size: 100%;font-style:italic;margin-top:2em;}</style><img src=//www.redditstatic.com/trouble-afoot.jpg alt=""><h2>all of our servers are busy right now</h2><h3>please try again in a minute</h3><p>(error code: 503)
    - SyntaxError: Unexpected token <
    -     at Object.parse (native)
    -     at /root/my_project/node_modules/snoocore/oauth.js:109:19
    -     at tryCatchReject (/root/my_project/node_modules/snoocore/node_modules/when/lib/makePromise.js:845:30)
    -     at runContinuation1 (/root/my_project/node_modules/snoocore/node_modules/when/lib/makePromise.js:804:4)
    -     at Fulfilled.when (/root/my_project/node_modules/snoocore/node_modules/when/lib/makePromise.js:592:4)
    -     at Pending.run (/root/my_project/node_modules/snoocore/node_modules/when/lib/makePromise.js:483:13)
    -     at Scheduler._drain (/root/my_project/node_modules/snoocore/node_modules/when/lib/Scheduler.js:62:19)
    -     at Scheduler.drain (/root/my_project/node_modules/snoocore/node_modules/when/lib/Scheduler.js:27:9)
    -     at process._tickCallback (node.js:355:11)]

**Comment by trevorsenior** [comment]
Thanks for reporting this. What type of authentication are you using?

What version of Snoocore are you using? Version 3 of Snoocore should properly handle HTTP 5xx errors on authentication. The older version does not support this and it will have a hard time when reddit servers are down on authentication (something that you have ran into).

**Comment by a9io** [comment]
Thanks, will do

**Comment by trevorsenior** [comment]
Yep, and if you do run into modhash issues please bother! Even unauthenticated calls go through OAuth (Application only OAuth) so it shouldn't occur. 

I'll close this issue for now. If it occurs in version 3 of the library please reopen the issue. If you have any questions on migrating over to version 3 of the library, feel free to ask on [gitter.im](https://gitter.im/trevorsenior/snoocore)

**Comment by a9io** [comment]
cool, thanks
