### ISSUE TITLE
Multiple retrievals of access_token

### ISSUE THREAD

**Issue by saiichihashimoto** [trevorsenior/snoocore#128]
When there's no ```access_token``` set and two requests are made in parallel, they each fire off a request for ```access_token``` individually instead of doing it once and using the same ```access_token```. Subsequent requests seem to use the ```access_token``` that was returned last.

[This screenshot](http://i.imgur.com/OeBe7Fq.png) illustrates the issue.

**Comment by denizdogan** [comment]
For what it's worth, I can't reproduce this issue. The screenshot link doesn't seem to work anymore.

**Comment by saiichihashimoto** [comment]
I don't know if this is still happening, and I don't really remember what's going on. Closing since it doesn't seem to actually be an issue.
