### ISSUE TITLE
Snoocore is too awesome.

### ISSUE THREAD

**Issue by go1dfish** [trevorsenior/snoocore#132]
Just wanted to say thanks.  This is a really awesome API, and I feel like I've built some really cool stuff with it.

I'm retiring from reddit, so there probably won't be many more builds from me, but here's what I did with Snoocore and Ember.js

https://modlog.github.io/#/monitor

https://fair-share.github.io

https://politicbot.github.io

https://github.com/go1dfish/politic-bot

Consider it all available under dual licensing MIT and WTFPLv2

I think Snoo can usher in a new age of reddit, it's just that good.

https://www.reddit.com/r/self/comments/36ibh5/ushering_in_a_new_age_of_transparency_and/

My final gift to reddit is here http://reddit.com/r/snew

Snew is what reddit was meant to be named before kn0thing and jedberg realized they couldn't afford the domain.  My hope is that it can resurrect what reddit was meant to be.

None of this would have happened without snoocore.

Farewell friends, I'll see you in other repositories.

    /u/go1dfish - code is law

**Comment by damianb** [comment]
move to close, notabug :p

**Comment by go1dfish** [comment]
+1 wontfix - functionality expected

**Comment by trevorsenior** [comment]
I've been keeping up with your apps here and there, quite impressive!

> Just wanted to say thanks. This is a really awesome API, and I feel like I've built some really cool stuff with it.

D'aww. You have put my own creation to *real* use before I ever could, and it's been more than a year since I've started working on this. Maybe some day I'll get around to finishing a project. Though...

> I'm retiring from reddit [...]  I'll see you in other repositories.

I feel the same way. This library has come to a state where there aren't so many issues so I can move onto other things.

**Comment by go1dfish** [comment]
> Just wanted to say thanks. This is a really awesome API, and I feel like I've built some really cool stuff with it.

[I have not even started](https://zh.reddit.com/domain/zh.reddit.com/)

If the admins find their own tools to be unacceptable platforms for disruption; perhaps they will feel differently about my own.

[Tomorrow is when the fun starts](https://www.reddit.com/r/POLITIC/comments/375fgk/失陪了_the_only_safe_space_of_reddit_rests_in_the/)

http://threevirtues.com
