### ISSUE TITLE
'api/v1/me' call failing after explicit OAuth when testing

### ISSUE THREAD

**Issue by aniforprez** [trevorsenior/snoocore#133]
I'm writing an application in node.js.

This is my configuration.
```javascript
var reddit = new snoocore({
	userAgent: '/u/abcd wxyz@0.0.0',
	oauth: {
		type: 'explicit',
		duration: 'permanent',
		key: 'XXXX',
		secret: 'YYYY',
		redirectUri: 'http://localhost:8080/auth/callback',
		scope: ['history', 'identity']
	}
});
```
The user agent, key and secret have been removed (just in case).

Within the OAuth callback route I am writing the following code
```javascript
app.get('/auth/callback', function(req, res) {
	var authCode = req.query.code;
	reddit.auth(authCode).then(function(refreshToken) {
		return reddit('/api/v1/me').get();
	}).then(function(result) {
                ...
	}).catch(function(err) {
		console.log(err);
	});
});
```

I get an error `'This call failed. Does this call require a user? ... etc` with a response code of `403`. This error only seems to happen when I test the api calls using Mocha and Supertest. In normal cases it seems to work just fine...

**Comment by trevorsenior** [comment]
In test cases you need to simulate the user authorizing your application with reddit. This can be done with PhantomJS for instance to control the browser & click accept.

This is exactly what I do to test Snoocore. Feel free to take a look at [the TestServer.js code](https://github.com/trevorsenior/snoocore/blob/3.0.2/test/src/TestServer.js) and [how I use it](https://github.com/trevorsenior/snoocore/blob/3.0.2/test/src/OAuth-test.js#L270) in my test cases to automatically authenticate.

Instead of going through the hassle of going through this for your test cases as I have, I would recommend fetching a refresh token, and using that in your test cases, e.g.

```javascript
reddit.refresh(REFRESH_TOKEN).then(function() { /* test case here */ });
```

Though I do not know exactly what you are testing / this may not work for you.

I am going to close this issue as it isn't a problem with the library, but we can continue the discussion on the best way to go about testing your code using Snoocore.

**Comment by aniforprez** [comment]
Thanks!

I'm creating an application which fetches a reddit user's saved posts. The server is written in nodejs where I want to fetch the posts and send them over to the client. I want to test authenticated and unauthenticated requests to the server using Mocha so changes in the future don't break without me knowing.

My problems come with how to authenticate the test runner. Searching online got me no results so how I'm currently testing is by using NightmareJS which is a framework built over PhantomJS to go through the reddit authentication flow i.e. entering a username and password, clicking login, clicking accept at the next screen and fetching the redirect URL containing the Auth code. I make a supertest request with this redirectURL and I actually do get a valid refresh token. But when I make any reddit API requests after authentication, it gives the error shown above.

If you have any suggestions on how to test the OAuth flow I would be extremely grateful.

**Comment by trevorsenior** [comment]
> I make a supertest request with this redirectURL and I actually do get a valid refresh token. But when I make any reddit API requests after authentication, it gives the error shown above.

If you are getting back a valid refresh token that is interesting. Is the code public anywhere? I can take a look at it after work and see if I notice anything out of the ordinary.

**Comment by aniforprez** [comment]
Oh yeah, it's public.

https://github.com/aniforprez/persnoo/blob/master/server.js#L108

The link takes you to the catch statement where the error is thrown.

**Comment by aniforprez** [comment]
Hey, not to be a bother but did you have a look at the code?

**Comment by trevorsenior** [comment]
Sorry for the later response (and thanks for the ping!)

I modified the tests file to only run one test case:

```javascript
it.only('should fetch saved posts when logged in', function(done) {
```

Then ran the tests with:

```
$ npm install
$ ./node_modules/.bin/mocha app/tests/server.test.js
```

But then get a bunch of output like this:

```
  authentication
phantom stdout: TypeError: null is not an object (evaluating 'document.querySelector(selector).focus')


phantom stdout:   phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3

phantom stdout: TypeError: null is not an object (evaluating 'document.querySelector(selector).focus')
// and so on...
```

What is your particular setup / version of phantomJS are you using?

**Comment by aniforprez** [comment]
I'm using phantomjs version 2.0.0. And the way you ran your tests was correct. I guess the version of phantom may be causing the error because when travis runs the tests it seems to run just fine.

**Comment by aniforprez** [comment]
Hi there!

I think for now I'll proceed developing my application with failing tests because there seems to be some other issues at play here. If you feel my method of testing is wrong or there is some way to fix this, please do get back to me.

Thanks for the support so far!

**Comment by trevorsenior** [comment]
Hey again. I couldn't get past the error message -- I'm also running Phantom 2.0.0. Testing early on is always nice, but not always the best experience! 

Please bother me on any Snoocore related issues you may run into & sorry I wasn't much help in debugging your test cases.

**Comment by aniforprez** [comment]
I'll keep trying to solve this and if I get anywhere, I'll try pinging you here.

When not testing, the library works superbly. This is really good work!
