### ISSUE TITLE
OAuth-less mode (for browser extensions)

### ISSUE THREAD

**Issue by empyrical** [trevorsenior/snoocore#134]
The reddit admins don't seem to mind the case of browser extensions (like RES or the moderator toolbox) not using OAuth at all and just using the user's cookies for their requests. Even their official JS wrapper (https://github.com/reddit/snoode) seems to support this way of working.

Would you be open to a pull request that allows snoocore to operate without OAuth?

**Comment by trevorsenior** [comment]
Hey there,

This would be a browser-only addition that would detect & use cookies for authentication if Snoocore was injected into the reddit page / domain, right? That's how RES works & I assume that's what you're looking for.

As long as you are not looking to authenticate with username/passwords via a cookie based login I'm actually okay with this. Snoocore would be using the cookies already stored on reddit's domain.

I've been away from this project for some time now. If you really want to work on this feel free to, else keep this issue open and I'll get to it eventually. 

I was thinking it could just be an initial option such as:

```javascript
new Snoocore({
    userAgent: 'identify your app here',
    useBrowserCookies: true, // auto authenticates with browser cookies
    oauth: { /* not needed anymore*/ }
})
```

**Comment by empyrical** [comment]
Yeah, all that would need to be done is disable the fetching of the OAuth token, and then `xhr.withCredentials = true;` would need to be set inside of the function that does the actual request. If you decide to switch to use `fetch()` in the future, you'd need to do this:

 ```js
fetch('/r/secretSub', { credentials: 'include' });
```

I'll have a stab at doing this (using the config name in your example, `useBrowserCookies`) and whenever I finish it I'll send a PR your way to look over!

The extension I'm making handles stylesheet images, so I'll also be sending you a PR that lets file uploading handle a `Blob`

**Comment by trevorsenior** [comment]
Alright @empyrical, take a stab at it and if it's too much I'll be glad to implement it.

There will be a minor complication with the domains, e.g. oauth.reddit.com vs. www.reddit.com on the endpoint calls if it is using cookie endpoints / etc.

Forcing [this.serverOAuth](https://github.com/trevorsenior/snoocore/blob/master/src%2FUserConfig.js#L21) to be the same value as `this.serverWWW` if `useBrowserCookies` is enabled _should_ be enough to ensure that all endpoints are using the `www` domain vs. the `oauth` domain.

**Comment by trevorsenior** [comment]
As for XHR, that file is here:

https://github.com/trevorsenior/snoocore/blob/master/src%2Fhttps%2FhttpsBrowser.js

There may not be any harm in setting `xhr.withCredentials = true;` for all requests, but I'd have to test that thoroughly (e.g. have an OAuth session and check that it does not use the use authenticated with cookies / etc)

**Comment by empyrical** [comment]
It ignores the user cookies if you send an oAuth request (tried while messing around with `httpsBrowser.js` last night), but to be safe and prevent potential weird behavior in other browsers I think it might be best to only set it if `useBrowserCookies` is true
