### ISSUE TITLE
Automatic oauth token refresh

### ISSUE THREAD

**Issue by cmcarey** [trevorsenior/snoocore#140]
Can't see docs on this, but does the token automatically refresh after the hour?

**Comment by trevorsenior** [comment]
What type of OAuth are you using to authenticate? It depends on what type of OAuth you are using.

**Comment by trevorsenior** [comment]
Explicit & Script based OAuth will automatically refresh the access token.

**Comment by cmcarey** [comment]
Yep, script based.  Thanks trevorsenior.

**Comment by trevorsenior** [comment]
No problem. I'll update the docs for the script based OAuth a bit.
