### ISSUE TITLE
Handling ratelimit errors

### ISSUE THREAD

**Issue by krazyjakee** [trevorsenior/snoocore#145]
> Potentially unhandled rejection [1] Error: 

When I get a rate limit error, the application dies. How can I handle that? Can you provide example code?

> you are doing that too much. try again in 6 minutes.

> /node_modules/snoocore/node_modules/when/lib/decorators/unhandledRejection.js:80

**Comment by damianb** [comment]
https://snoocore.readme.io/docs/events#section--rate_limit_reached-

alternatively, look at when's documentation on how to handle errors.

**Comment by trevorsenior** [comment]
@krazyjakee You app will die if you don't handle the rejection. Use [`.catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) to catch it & do things with it. 

```javascript
reddit('/hot').get().then(/* ... */).catch(function(error) { /* ... */ });
```

As damianb mentioned there are some events that you can listen into to get back more information.

**Comment by krazyjakee** [comment]
>  Use .catch

Aha! Thanks very much!
