### ISSUE TITLE
cannot find in docs

### ISSUE THREAD

**Issue by chovy** [trevorsenior/snoocore#153]
How do I delete a comment by id?

**Comment by devjunkORG** [comment]
Hi! This is more related to the usage of the reddit API itself than just Snoocore, since all you need to know is how to make a call. 

```
const deleteComment = reddit('/del').post({
  id: '[fullname](https://www.reddit.com/dev/api#fullnames)',
});
```

See docs here: https://www.reddit.com/dev/api#POST_api_del
