### ISSUE TITLE
Support reddit live threads (websocket)

### ISSUE THREAD

**Issue by damianb** [trevorsenior/snoocore#41]
http://www.reddit.com/dev/api/#section_live

Looks like it's been recently added.  Might need special handling with the WS bit.

**Comment by damianb** [comment]
Thinking about this for a while. This should probably be considered a red herring, only to be implemented in another library - possibly on top of snoocore itself.

**Comment by trevorsenior** [comment]
I'm still open to it being included in here, I just haven't given it much thought. If you do make another library that handles websockets I'll be glad to link to it in the README.
