### ISSUE TITLE
Add support for html decoding

### ISSUE THREAD

**Issue by trevorsenior** [trevorsenior/snoocore#79]
Discussion on this can be seen here: https://github.com/trevorsenior/snoocore/issues/77#issuecomment-69458529

HTML decoding globally (PRAW-like). The configuration gains an extra value:

```javascript
var reddit = new Snooroce({
  userAgent: 'test',
  oauth: { /* ... */ },
  decodeHtmlEntities: true // default false
});
```

Another way to handle this is *per call*:

```javascript
reddit('/about/edit.json').get({created: true}, {decodeHtmlEntities: true}).then(/* */)
```

Both methods will be supported, and can be used at the same time (per call will override the global settings).

**Comment by trevorsenior** [comment]
released in 2.2.0

**Comment by trevorsenior** [comment]
@tamadra let me know how this new feature works out for you.

**Comment by tamadra** [comment]
Thanks for all the good work!
