### ISSUE TITLE
Clarify "per call options"

### ISSUE THREAD

**Issue by damianb** [trevorsenior/snoocore#88]
Few things that come to mind. "Per call options" is a bit awkward, though I don't know why. Perhaps Call (or query) context options? Overrides? Dunno.

The page should also, probably, list and then nav to the various options available at the top, now that there's several available.

Stating up top that these options take priority (no matter the options set during authentication) would be better than putting it in each one's description.  Basically, the description for decodeEntities could be moved to the top and made more generic, since it applies to all options anyways.

Retry attempts / retry delay should probably link to the documentation for the global setting, imho.

**Comment by trevorsenior** [comment]
Yes, I agree that the documentation on this matter has gotten a bit out of hand. I'll address this issue and steal the idea's you've presented and update the docs. Thanks!
