### ISSUE TITLE
Retried 5XX endpoints stil generate error output

### ISSUE THREAD

**Issue by go1dfish** [trevorsenior/snoocore#89]
It looks like that when Snoocore retries 5XX api calls it still generates unavoidable stderr output.

I'd like to see this output get treated as a warning log or not logged at all until snoocore gives up on the request entirely.  Or it may be this is already the case and I'm just seeing these?

In either case, options may be helpful here for those who don't want stderr output for retried attempts.

I have notifications set up for when my bot writes to stderr and it would be ideal if this only happened due to unrecoverable issues.

**Comment by trevorsenior** [comment]
I'll have to see if any lingering `console.logs` were left in, I'll address this quickly. Thanks for the notification.

**Comment by trevorsenior** [comment]
@go1dfish What does the error message say? I'll patch this quickly but a search through the current project didn't yield any logging. Sorry for the inconvenience.

**Comment by go1dfish** [comment]
No worries, it's still better than it was, no inconvenience at all.

I don't have one of the messages handy but I'll paste it next time I see it.

**Comment by go1dfish** [comment]
Error: Failed to access the reddit servers (HTTP 5xx)
    at /home/alex/politic-bot/node_modules/snoocore/Snoocore.js:348:12
    at tryCatchReject (/home/alex/politic-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/alex/politic-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/alex/politic-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/home/alex/politic-bot/node_modules/snoocore/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/alex/politic-bot/node_modules/snoocore/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/alex/politic-bot/node_modules/snoocore/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)

Checked out the code and it looks like this is only happening once retries are exhausted; so working as it should.

Nothing to see here.  Move along

**Comment by damianb** [comment]
Hm. Defaults are to retry after three seconds, ten times. Maybe the default needs to be a bit more sensible - if reddit is 500'ing, then it's not likely that within thirty seconds it'll have recovered for sure. 

At the very least, imho if it exhausts retries, the error message itself should state so as an addendum. Perhaps modify the error message, append to it "(all $num reattempts exhausted)" or something?

**Comment by trevorsenior** [comment]
Thanks for the input. I have some work ahead of me to close these issues that have been brought to light in the `2.5.0` release.

@go1dfish The defaults are going to be adjusted to handle this issue in the future for most users, but if you are running a long running bot you may want to set the `retryAttempts` even higher than the proposed new defaults.
