### ISSUE TITLE
Snoocore in browser makes /api/info call without .json

### ISSUE THREAD

**Issue by go1dfish** [trevorsenior/snoocore#92]
Trying to do reddit('/api/info').get({id: 't3_2vptu5'})....

In snoocore causes a fetch without using .json:

https://www.reddit.com/api/info?id=t3_2vptu5

This ends up returning {} and causes errors if decode entities is turned on.

Seems to have the same behavior with by_id

**Comment by trevorsenior** [comment]
Similar to the `/duplicates` endpoint, it's another documentation issue on reddit's end. It needs to specify that it takes `[.json | .xml]` *and* also specify that it's a listing (formally, not just in the docs for the endpoint. I'll patch it over in their code. `reddit.raw` can be your faithful placeholder as this gets resolved.

**Comment by go1dfish** [comment]
Cool, between the two of us we should end up fixing all the docs at this rate.  No rush here.


I'm playing around with building a browser based reddit client.  Do you happen to know if it's possible to get write access via OAuth somehow?  Preferably in a way that would allow my client to stay full js without any server side component?

**Comment by damianb** [comment]
@go1dfish Is something not working as far as implicit oauth access via snoocore's browser builds, then?

**Comment by damianb** [comment]
(also, I'm still waiting on reddit to document reddit/reddit#1147 myself, ugh)

**Comment by damianb** [comment]
```
Error: Invalid path provided. Check that this is a valid path.
https://www.reddit.com/user/$username/submitted.json
```

http://www.reddit.com/dev/api/#GET_user_{username}_submitted

Similar issue here (still).

**Comment by go1dfish** [comment]
Oh I haven't tried doing oauth for browser access at all yet and have been sticking to read only calls.  I was more wondering if in general it was possible to have a JS based app that authenticated clients and didn't have to maintain any secrets of its own.  End goal would be hosting purely on something like s3 or even github pages.

**Comment by trevorsenior** [comment]
Yes, you can authenticate with Implicit based OAuth in 100% client side javascript. It does not require any secrets to be used, and everything except file uploads ( #9 ) should work. The only downside is that it will only stay authenticated for an hour before the access token needs to be renewed. 

I'm actually working on a project hosted on GitHub pages at the moment (I think it's private) that authenticates this way.

**Comment by trevorsenior** [comment]
@damianb I've started a new repository I'll work on later next week that will test **all** of reddit's endpoints against Snoocore. The goal would be to submit a single pull request that will fix all of the documentation issues.

**Comment by go1dfish** [comment]
I just pushed up my code and here is my currently read only client running on github pages:

http://politicbot.github.io/#/r/POLITIC/

http://politicbot.github.io

https://github.com/PoliticBot/vforreddit

The idea is to recreate reddit at the DOM level as an ember app using the API.  This way subreddit stylesheets still work and people can add on/modify functionality from there.

If no server functionality at all is required, it lowers the barrier to entry a lot and will let sub-reddits try out some radically different UX or even just small improvements.

**Comment by damianb** [comment]
@trevorsenior sweet. right now i have two queries that are stuck in raw mode until then, alas.

@go1dfish As far as tokens go, you -could- make it work using HTML5 localStorage, for write access.

**Comment by trevorsenior** [comment]
I'm still waiting to hear back from reddit on the PR; however, this may not matter in Snoocore version `3.0.0`. We should be able to drop `reddit.raw` completely. **Every** call to reddit will go through the domain `https://oauth.reddit.com` in `3.0.0`.

```javascript
reddit.raw('https://oauth.reddit.com/foo/bar.json');
// becomes
reddit('/foo/bar.json');
```
We will still rely on the documentation parsing to check scopes, fill in extensions, determine listings, auto-fill in `api_type: 'json'`, and more... **BUT** the following error will no longer exist:

> Error: Invalid path provided. Check that this is a valid path.

Instead, `reddit('/path/here')` will be more lenient and let any path through. If it does not match anything that was parsed from the documentation it'll give it a go anyway using `oauth.reddit.com`. If it works, great! If not it'll come back with an error.

**Comment by damianb** [comment]
Hmm - removing the path checking will be a positive change imo, though I would hope there's still the possibility of doing string formatting within the call for syntatic sugar, instead of us having to string.format ourselves (because lazy).

**Comment by trevorsenior** [comment]
@damianb are you referring to:

```javascript
reddit('/some/$variable/here').get({ $variable: 'value' });
```

? If so, that will still be supported.

**Comment by damianb** [comment]
yep

**Comment by trevorsenior** [comment]
I'm going to close this issue for now as it is already implemented / fixed in the 3.x.x branch of the library. Feel free to discuss it further here, but this will not be patched in the current 2.x.x version of Snoocore.

Expect the 3.x.x release of Snoocore towards the end of this week / beginning of next week. I hope it does not break anything too terribly *crosses fingers*.
