### ISSUE TITLE
Implicit OAuth logout?

### ISSUE THREAD

**Issue by go1dfish** [trevorsenior/snoocore#93]
May just be a documentation issue, but is there a way to log once you are authenticated?

**Comment by trevorsenior** [comment]
`reddit.deauth()` is what you need to call.

The information was in the implicit / explicit documentation but left it out in the script section. It's now been included in there as well. Once cookie based authentication is gone the structure of the documentation for OAuth will change to address this to avoid duplicate information.

**Comment by go1dfish** [comment]
Tried, using this, and it attempts to make a call against:

https://ssl.reddit.com/api/v1/revoke_token

Which fails the OPTIONS preflight request:

 XMLHttpRequest cannot load https://ssl.reddit.com/api/v1/revoke_token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 401.

**Comment by trevorsenior** [comment]
Oh right you're using implicit based OAuth and not Script based in your latest project. I'll relabel / reopen this issue.

**Comment by trevorsenior** [comment]
I've reproduced the results you're experiencing. I've made a [new post](https://www.reddit.com/r/redditdev/comments/2w8c2o/manually_revoking_an_access_token_with_an_app/) in /r/redditdev and will see if I can get any help there.

**Comment by trevorsenior** [comment]
It's been awhile, but this should be fixed on reddit's end now. I'll check it out in the next few days.

**Comment by trevorsenior** [comment]
Seems like it is working (Issue #119 had the same problem).
