### ISSUE TITLE
Version 3.0.0 - discussion (changes, new features, etc.)

### ISSUE THREAD

**Issue by trevorsenior** [trevorsenior/snoocore#94]
Anything and everything related to 3.0.0 can be discussed here. This is the chance to break backwards compatibility. The major change in this version will the the removal of cookie based authentication and all of the changes that come with it.

Milestone (and related issues): https://github.com/trevorsenior/snoocore/milestones/3.0.0

**Comment by trevorsenior** [comment]
Removal of `reddit.raw`. Brought up in https://github.com/trevorsenior/snoocore/issues/92#issuecomment-74910770. The functionality of `reddit.raw` will be merged into the main `reddit('/path/here')` call because all endpoints will use `https://oauth.reddit.com`.

There may be the one-off case where we may want to make a call *not* using `oauth.reddit.com`. This can be supported as another [call context option](http://tsenior.com/snoocore/callContextOptions.html) / a global setting.

**Comment by go1dfish** [comment]
The approach you bring up for removing reddit.raw sounds like a good one.

You could still include the doc checking and have a flag to throw warnings for undocumented calls.

**Comment by trevorsenior** [comment]
## OAuth Configuration Changes

**non-breaking change**

Remove the `login` option, and bundle username/password into `oauth`. Will keep backwards compatibility with `login: { username: '', password: '' }`

Change `consumerKey` -> `key` and `consumerSecret` -> `secret`  in `oauth` configuration. `consumerKey` and `consumerSecret` will continue to work.

**Comment by damianb** [comment]
IMO, deprecate consumerKey and consumerSecret completely. If you're going to make a breaking change, do it. No need to half-ass, just document the breaking changes well and we'll all be fine.

**Comment by trevorsenior** [comment]
## Removal of `reddit.getAuthUrl`

**breaking change**

Should change to `reddit.getExplicitAuthUrl`

## Removal of OAuth types `web` & `installed`

**breaking change**

Should convert to `explicit`

**Comment by damianb** [comment]
Thought: Use of an authentication agent may be useful for managing multiple authentication contexts. Unless explicitly requested (by a function call?) or provided, it should be invisible to the end user.

**Comment by damianb** [comment]
Further thought: agent should be as primitive as possible, in order to easily serialize it. If possible, making it just a js object would be best - allowing for authentication information to be easily cached and rotated between processes, servers if necessary.

**Comment by trevorsenior** [comment]
This is how authentication used to work before it was stuck in the initial configuration. It still works this way under the covers so it would be possible to have a function call to get / set the authentication data manually.

```javascript
var reddit = new Snoocore();
reddit.auth().then(function() {
  reddit.getAuthData(); // object containing the auth data
})
```

and later in another process if the authentication data isn't expired:

```javascript
reddit.setAuthData(/* auth data object from before */)
// can now make authenticated calls
```

Is that what you mean by an authentication agent?

**Comment by damianb** [comment]
That would work well, imo - just need to expose something (say a property or something?) to indicate if we're authenticated and possibly who as - though really, that could just be determined by getting the auth info itself. Hrrm.

**Comment by trevorsenior** [comment]
In the latest `wip-3.0.0` branch there are internal functions that'll determine if we're authenticated that can be exposed:

https://github.com/trevorsenior/snoocore/blob/714242cc47c36d97ae7c27486a3d27869a69721a/Snoocore.js#L121

There are a number of other functions in there that I've thrown in to help make the library more readable & easier to approach / maintain.

**Comment by trevorsenior** [comment]
Continued discussion from: https://github.com/trevorsenior/snoocore/issues/101#issuecomment-76646591

@damianb As for your first point it would be a pre-3.0 take of the problem. It wouldn't hurt to leave them in to set the access token / refresh token individually.

- - -

As for the timeouts / throttle issues involved with sharing a single Snoocore instance, I think that a more extreme overhaul can be introduced in 3.0 - something that'll manage multiple Snoocore instances and abstract away this problem all together. This would basically bring in what I'm already doing in my other project with refresh tokens to index multiple instances, but allow the users to pick their ID's for each instance.

A rough idea of how it would work (very high level):

```javascript
var snoocore = require('snoocore');

// same as `new Snoocore()` in 2.x.x
var user = snoocore.getClient(/* initial config */); 
```

With a client cache:

```javascript
var snoocore = require('snoocore');

// new way to handle multiple client instances
var cache  = snoocore.getClientCache(/* same initial config */);

// get a client by id
var id = 'someid';
var user1 = cache.getClient(id); // uses initial config to setup this client
var user2 = cache.getClient('foobar');
```

We're requesting a new client from the cache by an id. If it exists in the cache, we can use it. Else, we just create a new instance indexed by the id given and store it in the cache. Cache implementation details are left out for sake of simplicity.

In the context of a web application, it may look something like this:

```javascript
var app = express();
var snoocore = require('snoocore');
var cache = snoocore.getClientCache(/* ... */);

app.get('/me', function(req, res) {
  var userId = req.cookies.userId; // get user id from cookies

  // get relevant information from the database about this user by id
  var refreshToken = getRefreshTokenFromDB(userId);
  var accessToken = getAccessTokenFromDB(userId);

  // go ahead and get the reddit client associated with this user id
  var reddit = cache.getClient(userId);

  // set the auth data for this client
  reddit.setAuthData({ refreshToken: refreshToken, accessToken: accessToken });

  // make a call to reddit.
  return reddit('/api/v1/me').get().then(res.send);
});
```

**side notes**

- There needs to be a new event `access_token_renewed` that contains the new access token and the client id associated with it so database users can update their access tokens.

- Likewise, `access_token_expired` will need to have a reference to which client id it is referring to.

- - -

This is far from finalized. It's just one idea that I came up with on handling multiple instances within the library. Please critique it heavily if you'd like. I'm sure I will be throughout this next week :wink:.

**Comment by trevorsenior** [comment]
nah, I won't support the client cache - that's getting way out there in terms of what this library does. I may make it a separate project that I'll reference from Snoocore.

**Comment by trevorsenior** [comment]
I think the *only* thing holding back this release is the fact that Application Only OAuth is not working in browser based JavaScript:

https://www.reddit.com/r/redditdev/comments/2xdsix/application_only_oauth_for_browser_based/

**Comment by trevorsenior** [comment]
Closing this as 3.0.0 has been released.

@stuartpb I know I redirected you over here from #122—open a new issue if you want to discuss a better way to handle the OAuth web flow with multiple accounts. Thanks.
