### ISSUE TITLE
How can One get saved posts and comments?

### ISSUE THREAD

**Issue by techsin** [trevorsenior/snoocore#96]
Say i want to get this /user/userId/saved/

**Comment by trevorsenior** [comment]
Hey there, 

For this endpoint you're going to need to authenticate. You should use OAuth for this. There are various OAuth choices when setting up an application, but for this example I'll be using `script` based OAuth as it is the easiest to demonstrate.

You are going to use this endpoint: https://www.reddit.com/dev/api#GET_user_{username}_saved

The working code (replace `process.env.xxx` with your values):

```javascript
var Snoocore = require('snoocore'); // version 2.7.0
console.log(Snoocore.version);

// setup snoocore with your OAuth information
var reddit = new Snoocore({
  userAgent: 'myapp v1 /u/username',
  login: {
    username: process.env.REDDIT_USERNAME,
    password: process.env.REDDIT_PASSWORD
  },
  oauth: {
    type: 'script',
    consumerKey: process.env.REDDIT_SCRIPT_KEY,
    consumerSecret: process.env.REDDIT_SCRIPT_SECRET,
    scope: [ 'history' ] // the users saved posts requires the history scope
  }
});

// authenticate with the user
reddit.auth().then(function() {
  // call the endpoint we want to use... it is a
  // listing, so we can use the listing helper
  return reddit('/user/$username/saved').listing({
    $username: process.env.REDDIT_USERNAME,
    limit: 100
  });
}).then(function(slice) {
  // We now have a slice from the listing that
  // holds information from this portion
  // of this listing.
  console.log(slice);
});
```

Documentation:

- [Script based OAuth](http://tsenior.com/snoocore/oauth-script.html)
- [More Listing info](http://tsenior.com/snoocore/listings.html) - goes over what a slice is / etc.
- and more! let me know if anything is confusing in there and it can be made clearer.

**Comment by trevorsenior** [comment]
I'm closing this issue but feel free to reopen it if you have any further questions.
